SiteTitle: Cloud en français
Intro: L'infonuagique et plus encore
Description: Parlons du «cloud computing» en français

Image: content/images/Cloudenfrancais-logo3.png

PublishedUsesLastModifiedDate: false
LinkHideExtensions: false
LinksUseHttps: true
DateTimeDisplayCulture: "fr-FR"
